apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
- kind: ServiceAccount
  name: default
  namespace: argo
