# The generated secret token should be added as secrets to Github.
# See `.github/workflows/ci.yaml`.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-github-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-aggregate-to-edit
subjects:
- kind: ServiceAccount
  name: github
  namespace: argo
