---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
