apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-helm-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: helm/operator
    repoURL: https://github.com/minio/operator.git
    targetRevision: v6.0.3
    helm:
      releaseName: minio

  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: tenants.minio.min.io
    jsonPointers:
    - /spec/preserveUnknownFields

  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
