apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart.git
    targetRevision: v31.0.0
    helm:
      releaseName: traefik
      parameters:
      - name: service.type
        value: NodePort
      - name: ingressClass.enabled
        value: "true"
      - name: ingressClass.isDefaultClass
        value: "true"
      - name: ports.web.nodePort
        value: "80"
      - name: ports.websecure.nodePort
        value: "443"

  destination:
    namespace: traefik
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
