apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-helm-chart
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: charts
    repoURL: https://github.com/openebs/openebs.git
    targetRevision: openebs-4.1.0
    helm:
      releaseName: openebs
      parameters:
      - name: "engines.local.lvm.enabled"
        value: "false"
      - name: "engines.local.zfs.enabled"
        value: "false"
      - name: "engines.replicated.mayastor.enabled"
        value: "false"
      - name: localpv-provisioner.hostpathClass.isDefaultClass
        value: "true"

  destination:
    namespace: openebs
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
