---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/openebs
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/registry
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: registry
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/postgres-operator
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/traefik
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/cert-manager
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

