---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/openebs
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kube/postgres-operator
    repoURL: git@github.com:epsilonsquare/infra.git
    targetRevision: main
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
